Add debug logging

diff --git a/scripts/hooks/configure b/scripts/hooks/configure
--- a/scripts/hooks/configure
+++ b/scripts/hooks/configure
@@ -2,6 +2,15 @@
 
 set -e 
 
+logger "Configure snap!"
+
+if [ ! -f "${SNAP_DATA}/settings.conf" ]; then
+    logger "Settings-file is missing"
+    exit 1
+else
+    logger "Settings.conf exists, continue configure"
+fi
+
 snapctl get server | $SNAP/bin/update-settings "${SNAP_DATA}/settings.conf" update
 snapctl restart "${SNAP_NAME}.server"
 exit $?
diff --git a/scripts/hooks/connect-plug-configurations b/scripts/hooks/connect-plug-configurations
--- a/scripts/hooks/connect-plug-configurations
+++ b/scripts/hooks/connect-plug-configurations
@@ -1,5 +1,14 @@
 #!/usr/bin/env bash
 set -e
+logger "Connect plug!"
+
+if [ ! -f "${SNAP_DATA}/settings.conf" ]; then
+    logger "Settings-file is missing"
+    exit 1
+else
+    logger "Settings.conf exists, continue plug:configurations"
+fi
+
 snapctl set server.basepath.dir="${SNAP_COMMON}/configurations"
 snapctl set server.basepath.enforce=True
 snapctl get server | $SNAP/bin/update-settings "${SNAP_DATA}/settings.conf" update
diff --git a/scripts/hooks/install b/scripts/hooks/install
--- a/scripts/hooks/install
+++ b/scripts/hooks/install
@@ -1,8 +1,18 @@
 #!/usr/bin/env bash
 
 set -e
+
+logger "Copying ${SNAP}/settings.conf to ${SNAP_DATA}/settings.conf"
 cp "${SNAP}/settings.conf" "${SNAP_DATA}/settings.conf"
 
+if [ $? -ne 0 ]; then
+    logger "Failed moving settings.conf!"
+    exit 1
+else
+    logger "Moved settings.conf successfully!"
+fi
+
+logger "Read initial settings to snap"
 $SNAP/bin/update-settings "${SNAP_DATA}/settings.conf" "install" | while read LINE; do
     logger "${LINE}"
     snapctl set "${LINE}"
